"""
Django settings for aulatrack project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-i0zs+wbc0rtgz)&-5a!ft(=slfrh29@5n5vxg3+#m@ra9dquf1'

# Cambiar a False en Render
DEBUG = False

ALLOWED_HOSTS = [
    'prueba-render-0fd9.onrender.com',
    '.onrender.com',
    'localhost',
    '127.0.0.1',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_extensions',  #  quítalo si no está instalado en Render
    'usuarios',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

# ===============================
#  ARCHIVOS ESTÁTICOS  
# ===============================
STATIC_URL = '/static/'

# Dónde Django juntará todo para producción (Render usa esto)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Tus archivos están dentro de usuarios/static/
STATICFILES_DIRS = [
    BASE_DIR / 'usuarios' / 'static',
]

# WhiteNoise para producción
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ===============================
# MIDDLEWARE (incluye WhiteNoise)
# ===============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # <-- OBLIGATORIO
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'usuarios:home_page'
LOGOUT_REDIRECT_URL = 'usuarios:login'

ROOT_URLCONF = 'aulatrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aulatrack.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
